#!/bin/sh
balance=$(ledger --format "%(display_total)" -f $1 balance checking | cut -c 4-)
pad="       "
balance=$balance$pad
balance=${balance:0:7}
echo "$balance   -     +      D"
for i in {1..20}
do
	echo '_______|_____|_____|_______'
done

